server:
  port: 8080
spring:
  application:
    name: restaurant-service
  datasource:
    url: "jdbc:mysql://localhost:3307/restaurant_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true