server:
  port: 8080
spring:
  application:
    name: restaurant-service
  datasource:
    url: "jdbc:mysql://localhost:3307/restaurant_service_database_v2"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
#      physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: validate
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9095
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer





#
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3307/restaurant_service_database_v1"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: root
#    password: 12345678  # Driver MySQL
#  jpa:
#    hibernate:
#      ddl-auto: none  # Không tự động tạo bảng trong cơ sở dữ liệu
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect  # Cấu hình dialect cho MySQL 8
#  datasource:
#    hikari:
#      maximum-pool-size: 20  # Kích thước tối đa của pool kết nối (tùy chọn)
#  logging:
#    level:
#      org.hibernate.SQL: DEBUG  # In ra các câu lệnh SQL để theo dõi
#      org.hibernate.type.descriptor.sql: TRACE  # Hiển thị chi tiết về dữ liệu truy vấn
